site_name: VSCode Class
site_author: Adam Catching

theme:
  name: readthedocs
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-4 
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.indexes
nav:
  - 0. Introduction: https://vscode-class.readthedocs.io/
  - 1. Biowulf: https://vscode-class.readthedocs.io/biowulf/
  - 2. VSCode: https://vscode-class.readthedocs.io/vscode/
  - 3. Anaconda: https://vscode-class.readthedocs.io/anaconda/
  - 4. Python: https://vscode-class.readthedocs.io/python_intro/
  - 5. GitHub: https://vscode-class.readthedocs.io/github/
  - 6. Snakemake: https://vscode-class.readthedocs.io/snakemake/
  - 7. Singularity: https://vscode-class.readthedocs.io/singularity_page/