site_name: VSCode Class
site_author: Adam Catching

theme:
  name: readthedocs # or 'mkdocs'
  color_mode: auto
  user_color_mode_toggle: true
  features:
    - navigation.indexes
nav:
  - 0. Introduction: https://vscode-class.readthedocs.io/
  - 1. Biowulf: https://vscode-class.readthedocs.io/biowulf/
  - 2. VSCode: https://vscode-class.readthedocs.io/vscode/
  - 3. Anaconda: https://vscode-class.readthedocs.io/anaconda/
  - 4. Python: https://vscode-class.readthedocs.io/python_intro/
  - 5. GitHub: https://vscode-class.readthedocs.io/github/
  - 6. Snakemake: https://vscode-class.readthedocs.io/snakemake/
  - 7. Singularity: https://vscode-class.readthedocs.io/singularity_page/