site_name: VSCode Class
site_author: Adam Catching

theme:
  name: readthedocs 
  features:
    - navigation.indexes
nav:
  - 0. Introduction: index.md
  - 1. Biowulf: biowulf.md
  - 2. VSCode: vscode.md
  - 3. Anaconda: anaconda.md
  - 4. Python: python_intro.md
  - 5. GitHub: github.md
  - 6. Snakemake: snakemake.md
  - 7. Singularity: singularity_page.md